//
//  ReceiptDetailInteractor.swift
//  ItauChallenge
//
//  Created by Thiago Lima on 19/06/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReceiptDetailBusinessLogic
{
  func doSomething(request: ReceiptDetail.Something.Request)
}

protocol ReceiptDetailDataStore
{
  //var name: String { get set }
}

class ReceiptDetailInteractor: ReceiptDetailBusinessLogic, ReceiptDetailDataStore
{
  var presenter: ReceiptDetailPresentationLogic?
  var worker: ReceiptDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ReceiptDetail.Something.Request)
  {
    worker = ReceiptDetailWorker()
    worker?.doSomeWork()
    
    let response = ReceiptDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
