//
//  ReceiptDetailWorker.swift
//  ItauChallenge
//
//  Created by Thiago Lima on 19/06/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ReceiptDetailWorker
{
  func doSomeWork()
  {
  }
}
